name: Auto Fix Single Model Env

run-name: >-
  Reconstruct ${{ inputs.model }}
  on Python ${{ inputs.python_versions }}

on:
  workflow_dispatch:
    inputs:
      model:
        description: "MatBench submission name, without the matbench_v0.1_ prefix"
        required: true
        default: "TPOT"
        type: string

      python_versions:
        description: 'Python versions as valid JSON, for example ["3.8","3.9","3.10"]'
        required: true
        default: '["3.6","3.7","3.8","3.9","3.10","3.11","3.12"]'
        type: string

permissions:
  contents: read

jobs:
  reconstruct-environment:
    name: >-
      ${{ inputs.model }} / Python ${{ matrix.python_version }}

    strategy:
      fail-fast: false

      # Prevent all versions from running simultaneously.
      # This value can be increased or removed.
      max-parallel: 4

      matrix:
        python_version: ${{ fromJSON(inputs.python_versions) }}

    uses: ./.github/workflows/env-autofix-and-import-check.yml

    with:
      model: ${{ inputs.model }}
      python_version: ${{ matrix.python_version }}