name: Lock and Pack Single Model Env

run-name: >-
  Lock and pack ${{ inputs.model }}
  on Python ${{ inputs.python_versions }}

on:
  workflow_dispatch:
    inputs:
      model:
        description: "MatBench submission name, without the matbench_v0.1_ prefix"
        required: true
        default: "Ax_10_90_CrabNet_v1.2.7"
        type: string

      python_versions:
        description: 'Python versions as valid JSON, for example ["3.8"]'
        required: true
        default: '["3.8"]'
        type: string

permissions:
  contents: read

jobs:
  lock-environment:
    name: >-
      ${{ inputs.model }} / Python ${{ matrix.python_version }}

    strategy:
      fail-fast: false
      max-parallel: 2

      matrix:
        python_version: ${{ fromJSON(inputs.python_versions) }}

    uses: ./.github/workflows/check-env-and-export.yml

    with:
      model: ${{ inputs.model }}
      python_version: ${{ matrix.python_version }}
      system_dependencies: git